require('keybindings')
require('plugins')
require('options')
require('lualine-config')
require('bufferline-config')
require('nvim-autotag-config')
require('nvimtree-config')
require('blankline-config')
require('format-config')
require('autopairs-config')
require('telescope-config')
require('whichkey-config')
require("treesitter-config")
require('lsp')
require('dashboard-config')
require('toggleterm-config')
require('comment-config')
vim.cmd('colorscheme tokyonight') 
